// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBljeVPVLuWJhpOn97Fpkabmll8o1VyL-8',
    appId: '1:788643923827:web:6fb9eca9b520130ec7e706',
    messagingSenderId: '788643923827',
    projectId: 'improov-2026',
    authDomain: 'improov-2026.firebaseapp.com',
    storageBucket: 'improov-2026.firebasestorage.app',
    measurementId: 'G-08JRQH8FC5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYecdfXL37XiPWkIqXquGVpQTgSgw9o60',
    appId: '1:788643923827:android:8b36e0f672bc2726c7e706',
    messagingSenderId: '788643923827',
    projectId: 'improov-2026',
    storageBucket: 'improov-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbpw_89FhdU6P06C_9SQzjasQCjfRmn0A',
    appId: '1:788643923827:ios:7b08c558bd32e66ac7e706',
    messagingSenderId: '788643923827',
    projectId: 'improov-2026',
    storageBucket: 'improov-2026.firebasestorage.app',
    iosBundleId: 'com.example.improov',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbpw_89FhdU6P06C_9SQzjasQCjfRmn0A',
    appId: '1:788643923827:ios:7b08c558bd32e66ac7e706',
    messagingSenderId: '788643923827',
    projectId: 'improov-2026',
    storageBucket: 'improov-2026.firebasestorage.app',
    iosBundleId: 'com.example.improov',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBljeVPVLuWJhpOn97Fpkabmll8o1VyL-8',
    appId: '1:788643923827:web:eca22a5619ca3436c7e706',
    messagingSenderId: '788643923827',
    projectId: 'improov-2026',
    authDomain: 'improov-2026.firebaseapp.com',
    storageBucket: 'improov-2026.firebasestorage.app',
    measurementId: 'G-H6900HD2YV',
  );
}
