extend type Habit {
  """
  ✨ Implicit foreign key field based on `Habit`.`user`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  userId: UUID! @fdc_generated(from: "Habit.user", purpose: IMPLICIT_REF_FIELD)
}
extend type HabitLog {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "HabitLog", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `HabitLog`.`habit`. It must match the value of `Habit`.`id`. See `@ref` for how to customize it.
  """
  habitId: UUID! @fdc_generated(from: "HabitLog.habit", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `HabitLog`.`user`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  userId: UUID! @fdc_generated(from: "HabitLog.user", purpose: IMPLICIT_REF_FIELD)
}
extend type Task {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Task", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `Task`.`user`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  userId: UUID! @fdc_generated(from: "Task.user", purpose: IMPLICIT_REF_FIELD)
}
extend type User {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "User", purpose: IMPLICIT_KEY_FIELD)
}
