extend type Habit {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Habit", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Habit` table.
  """
  _count: Int! @fdc_generated(from: "Habit.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Habit` table where the `bestStreak` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  bestStreak_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Habit.bestStreak", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Habit` table where the `colorHex` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  colorHex_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Habit.colorHex", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Habit` table where the `currentStreak` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  currentStreak_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Habit.currentStreak", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Habit` table where the `description` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  description_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Habit.description", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Habit` table where the `goalDaysPerWeek` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  goalDaysPerWeek_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Habit.goalDaysPerWeek", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Habit` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Habit.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Habit` table where the `isArchived` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  isArchived_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Habit.isArchived", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Habit` table where the `isHabitMode` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  isHabitMode_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Habit.isHabitMode", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Habit` table where the `name` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  name_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Habit.name", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Habit` table where the `priority` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  priority_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Habit.priority", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Habit` table where the `reminderTime` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  reminderTime_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Habit.reminderTime", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Habit` table where the `startDate` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  startDate_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Habit.startDate", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Habit` table where the `userId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  userId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Habit.userId", purpose: QUERY_COUNT)
  """
  ✨ Sum the `bestStreak` field in the `Habit` table.
  """
  bestStreak_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Int @fdc_generated(from: "Habit.bestStreak", purpose: QUERY_SUM)
  """
  ✨ Sum the `colorHex` field in the `Habit` table.
  """
  colorHex_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Habit.colorHex", purpose: QUERY_SUM)
  """
  ✨ Sum the `currentStreak` field in the `Habit` table.
  """
  currentStreak_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Int @fdc_generated(from: "Habit.currentStreak", purpose: QUERY_SUM)
  """
  ✨ Sum the `goalDaysPerWeek` field in the `Habit` table.
  """
  goalDaysPerWeek_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Int @fdc_generated(from: "Habit.goalDaysPerWeek", purpose: QUERY_SUM)
  """
  ✨ Average the `bestStreak` field in the `Habit` table.
  """
  bestStreak_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Habit.bestStreak", purpose: QUERY_AVG)
  """
  ✨ Average the `colorHex` field in the `Habit` table.
  """
  colorHex_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Habit.colorHex", purpose: QUERY_AVG)
  """
  ✨ Average the `currentStreak` field in the `Habit` table.
  """
  currentStreak_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Habit.currentStreak", purpose: QUERY_AVG)
  """
  ✨ Average the `goalDaysPerWeek` field in the `Habit` table.
  """
  goalDaysPerWeek_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "Habit.goalDaysPerWeek", purpose: QUERY_AVG)
  """
  ✨ Minimum of the `bestStreak` field in the `Habit` table.
  """
  bestStreak_min: Int @fdc_generated(from: "Habit.bestStreak", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `colorHex` field in the `Habit` table.
  """
  colorHex_min: Float @fdc_generated(from: "Habit.colorHex", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `currentStreak` field in the `Habit` table.
  """
  currentStreak_min: Int @fdc_generated(from: "Habit.currentStreak", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `goalDaysPerWeek` field in the `Habit` table.
  """
  goalDaysPerWeek_min: Int @fdc_generated(from: "Habit.goalDaysPerWeek", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `reminderTime` field in the `Habit` table.
  """
  reminderTime_min: Timestamp @fdc_generated(from: "Habit.reminderTime", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `startDate` field in the `Habit` table.
  """
  startDate_min: Timestamp @fdc_generated(from: "Habit.startDate", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `bestStreak` field in the `Habit` table.
  """
  bestStreak_max: Int @fdc_generated(from: "Habit.bestStreak", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `colorHex` field in the `Habit` table.
  """
  colorHex_max: Float @fdc_generated(from: "Habit.colorHex", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `currentStreak` field in the `Habit` table.
  """
  currentStreak_max: Int @fdc_generated(from: "Habit.currentStreak", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `goalDaysPerWeek` field in the `Habit` table.
  """
  goalDaysPerWeek_max: Int @fdc_generated(from: "Habit.goalDaysPerWeek", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `reminderTime` field in the `Habit` table.
  """
  reminderTime_max: Timestamp @fdc_generated(from: "Habit.reminderTime", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `startDate` field in the `Habit` table.
  """
  startDate_max: Timestamp @fdc_generated(from: "Habit.startDate", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Habit.id", purpose: GLOBAL_ID)
}
extend type Task {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Task", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Task` table.
  """
  _count: Int! @fdc_generated(from: "Task.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Task` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Task.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Task` table where the `description` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  description_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Task.description", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Task` table where the `dueDate` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  dueDate_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Task.dueDate", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Task` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Task.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Task` table where the `isCompleted` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  isCompleted_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Task.isCompleted", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Task` table where the `name` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  name_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Task.name", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Task` table where the `priority` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  priority_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Task.priority", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Task` table where the `userId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  userId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Task.userId", purpose: QUERY_COUNT)
  """
  ✨ Minimum of the `createdAt` field in the `Task` table.
  """
  createdAt_min: Timestamp @fdc_generated(from: "Task.createdAt", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `dueDate` field in the `Task` table.
  """
  dueDate_min: Timestamp @fdc_generated(from: "Task.dueDate", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `createdAt` field in the `Task` table.
  """
  createdAt_max: Timestamp @fdc_generated(from: "Task.createdAt", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `dueDate` field in the `Task` table.
  """
  dueDate_max: Timestamp @fdc_generated(from: "Task.dueDate", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Task.id", purpose: GLOBAL_ID)
}
extend type User {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "User", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `User` table.
  """
  _count: Int! @fdc_generated(from: "User.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `email` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  email_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.email", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `passwordHash` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  passwordHash_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.passwordHash", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `username` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  username_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.username", purpose: QUERY_COUNT)
  """
  ✨ Minimum of the `createdAt` field in the `User` table.
  """
  createdAt_min: Timestamp @fdc_generated(from: "User.createdAt", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `createdAt` field in the `User` table.
  """
  createdAt_max: Timestamp @fdc_generated(from: "User.createdAt", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "User.id", purpose: GLOBAL_ID)
}
